const SPLASH_COLOR1 = '#3cd6e0';
const SPLASH_COLOR2 = '#acefe3';

const ONBOARDING_TEXT_BUTTON_COLOR = '60979e';

const STATUS_BAR_COLOR = '#4C676B';
const HOME_SCREEN_BACKGROUND_COLOR = '#f4f9ff';
const HOME_SCREEN_TEXT_COLOR = '#60979e';
const HOME_SCREEN_DOTTED_LINE_COLOR = '#e4e4e4';
const HOME_SCREEN_FLOATING_BUTTON_COLOR = '#629fa8';
const APP_BAR_SHADOW_COLOR = '#abdfeb';
const APP_BAR_TITLE_COLOR = '#ababab';
const TEXT_FIELD_BORDER_COLOR = '#40ababab';
const TEXT_FILED_HINT_COLOR = '#d4d4d4';
const DATE_PICKER_DIVIDER_COLOR = '#828282';
const DETAIL_TEXT_COLOR ='#505050';